// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRAKbP-B8-oe9OmEYYP-TZt3UpzF48xcE',
    appId: '1:216949105895:web:ca492b4c814f7660ef6e42',
    messagingSenderId: '216949105895',
    projectId: 'campus-atitus',
    authDomain: 'campus-atitus.firebaseapp.com',
    storageBucket: 'campus-atitus.appspot.com',
    measurementId: 'G-34ZQB7MZMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiccOnSRDZ2wqpBOmMkIOvIKu6FpQnaw4',
    appId: '1:216949105895:android:57e8b41dacfbc3ebef6e42',
    messagingSenderId: '216949105895',
    projectId: 'campus-atitus',
    storageBucket: 'campus-atitus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCokmy-Pu0kdpnLTDgHNx52XaqH1VSbRC0',
    appId: '1:216949105895:ios:d9fbe12eab1f694eef6e42',
    messagingSenderId: '216949105895',
    projectId: 'campus-atitus',
    storageBucket: 'campus-atitus.appspot.com',
    iosClientId: '216949105895-en6pi2et127fndqu1gho70buqks1vjsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMapsInFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCokmy-Pu0kdpnLTDgHNx52XaqH1VSbRC0',
    appId: '1:216949105895:ios:d9fbe12eab1f694eef6e42',
    messagingSenderId: '216949105895',
    projectId: 'campus-atitus',
    storageBucket: 'campus-atitus.appspot.com',
    iosClientId: '216949105895-en6pi2et127fndqu1gho70buqks1vjsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMapsInFlutter',
  );
}
